### ISSUE TITLE
Could not load file or assembly 'StyleCop.Analyzers, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by jackhj000** [rookxx/StyleCopAnalyzers.CLI#19]
**I got a error like this when run StyleCopAnalyzers.CLI.exe as below:**
C:\Users\xx\Downloads\csharp_test> **C:\ProgramData\Scan\StyleCopAnalyzers.CLI\StyleCopAnalyzers.CLI.exe check .**

Could not load file or assembly 'StyleCop.Analyzers, Culture=neutral, PublicKeyToken=null'. 系统找不到指定的文件。at System.Reflection.RuntimeAssembly.InternalLoad(ObjectHandleOnStack assemblyName, ObjectHandleOnStack requestingAssembly, StackCrawlMarkHandle stackMark, Boolean throwOnFileNotFound, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack retAssembly)at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, RuntimeAssembly requestingAssembly, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)at StyleCopAnalyzers.CLI.AnalyzerLoader.GetAnalyzers() in /home/runner/work/StyleCopAnalyzers.CLI/StyleCopAnalyzers.CLI/src/AnalyzerLoader.cs:line 34at StyleCopAnalyzers.CLI.StyleChecker.Check(CancellationToken cancellationToken) in /home/runner/work/StyleCopAnalyzers.CLI/StyleCopAnalyzers.CLI/src/Commands/StyleChecker.cs:line 75at StyleCopAnalyzers.CLI.Program.<>c__DisplayClass0_0.<b__1>d.MoveNext() in /home/runner/work/StyleCopAnalyzers.CLI/StyleCopAnalyzers.CLI/src/Program.cs:line 28--- End of stack trace from previous location ---at StyleCopAnalyzers.CLI.Program.Main(String[] args) in /home/runner/work/StyleCopAnalyzers.CLI/StyleCopAnalyzers.CLI/src/Program.cs:line 23

**OS info:** windows 10 x64,  a vm in VMware fusion
**.Net core:** 6.0
**StyleCopAnalyzers.CLI.exe version:** 1.1.0-winx64-core6.0

I'm not verify familiar with C# but should use static tools to analyze c# files now.
Should I install anything else? I'm looking forward for your help, thanks a lot.

**Comment by rookxx** [comment]
I see that you are running the exe directly, not getting it with nuget.
I suspect that the CommandLineParser dll file is not in the same hierarchy as the exe file.
Try running the command `dotnet publish -c Release` and put all published dlls in the same hierarchy.

**Comment by jackhj000** [comment]
> I see that you are running the exe directly, not getting it with nuget. I suspect that the CommandLineParser dll file is not in the same hierarchy as the exe file. Try running the command `dotnet publish -c Release` and put all published dlls in the same hierarchy.

Yes，I run the StyleCopAnalyzers.CLI.exe which is download from your released StyleCopAnalyzers.CLI-1.1.0-winx-64-core6.0.zip.  I unarchive the whole zip file.  I see that a CommandLine.dll file is already in the same dir with StyleCopAnalyzers.CLI.exe.  Can i directly use this CLI without install the [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) in additional？

**Comment by jackhj000** [comment]
e s

> > I see that you are running the exe directly, not getting it with nuget. I suspect that the CommandLineParser dll file is not in the same hierarchy as the exe file. Try running the command `dotnet publish -c Release` and put all published dlls in the same hierarchy.
> 
> Yes，I run the StyleCopAnalyzers.CLI.exe which is download from your released StyleCopAnalyzers.CLI-1.1.0-winx-64-core6.0.zip. I unarchive the whole zip file. I see that a CommandLine.dll file is already in the same dir with StyleCopAnalyzers.CLI.exe. Can i directly use this CLI without install the [StyleCopAnalyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) in additional？

I use dotnet command to install the cli, it works well now. thanks a lot.

**Comment by rookxx** [comment]
I'm glad it's resolved.
