### ISSUE TITLE
Publish on NuGet as dotnet tool

### ISSUE THREAD

**Issue by ghost** [rookxx/StyleCopAnalyzers.CLI#9]
It would be nice if this could be released on NuGet as dotnet-tool, see also https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools

This would make the integration in existing projects a lot easier.

**Comment by rookxx** [comment]
Thanks for the good suggestions.
I'll be giving this suggestion a try in the coming days!

**Comment by rookxx** [comment]
It took me a while.
I added support for dotnet tool.
